language: ruby
before_install:
  - gem update
  - gem --version
bundler_args: --without development
script: "bundle exec rake test SPEC_OPTS='--format documentation'"
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.3
env:
  - PUPPET_GEM_VERSION="~> 3.4"
  - PUPPET_GEM_VERSION="~> 3.5"
  - PUPPET_GEM_VERSION="~> 3.6"
  - PUPPET_GEM_VERSION="~> 3.7"
  - PUPPET_GEM_VERSION="~> 3.8"
  - PUPPET_GEM_VERSION="~> 4.2"
notifications:
  email:
    - john.zimm@gmail.com
